### ISSUE TITLE
Async await support

### ISSUE THREAD

**Issue by RupamShaw** [grrr-amsterdam/mysql-ssh#10]
Is this work with async await mysql2

```
const mysql = require('mysql2/promise');

// get the promise implementation, we will use bluebird
const bluebird = require('bluebird');

// create the connection, specify bluebird as Promise
const connection = await mysql.createConnection({host:'localhost', user: 'root', database: 'test', Promise: bluebird});

// query database
const [rows, fields] = await connection.execute('SELECT * FROM `table` WHERE `name` = ? AND `age` > ?', ['Morty', 14]);
```

how to acheive async await  using this library
```
const mysqlssh = require('mysql-ssh');
// const mysql= require('mysql2/promise')
const bluebird = require('bluebird');

const selectQuery=`SELECT * FROM table WHERE name='qq'`
const sshclient=  await mysqlssh.connect(
      {
        host: 'www.xxxx.com',
        user: 'xxyz',
        password: 'xyz',
      },
     {host:'localhost', user: 'root', database: 'test', Promise: bluebird}
    )

  const [rows, fields] = await sshclient.execute(selectQuery)

```

it gives error
```
TypeError: (intermediate value) is not iterable
```

**Comment by raideltorres** [comment]
Well I had the exact same issue and I solved by doing this

1 - Create the connection with await

`const client = await mysqlssh.connect( . . . );`

2 - Then you can create and execute your query like this

`const foundItem = await client.promise().query('SOME QUERY');`

Note: The `.promise()` is the one doing the magic
Note: This will result in a lot of data, not only the query results, so you will need to pick the data you need from that variable.

**Comment by efarinas** [comment]
@raideltorres  do you have an example? I cant exceute the query

**Comment by RupamShaw** [comment]
const mysqlssh = require('mysql-ssh');

const selectQuery=`SELECT * FROM table WHERE name='qq'`
const sshclient=  await mysqlssh.connect(
      {
        host: 'www.xxxx.com', // or put IP
        username: 'xxyz',
        password: 'xyz',
      },
     {host:'localhost', port:3306, user: 'root',  password:'pass',database: 'test'}
    )

    async function getDetailed() {
      return new Promise(function (resolve, reject) {
        sshclient.query(selectQuery, async function (err, results, fields) {
          console.log("starting to get query");
  
          if (err) {
            console.log("Some issues in gettin query, err thrown");
            mysqlssh.close();
            reject(err)
           }

          console.log("fetched  query results length", results.length);
    
          if (results.length >0) {
            console.log(" results length is 0")
            mysqlssh.close();
            resolve(results);
          }
       }) // sshclient
     }) // newPromise
  } // getDetailed()
const result = await getDetailed()

This will be resolved
